/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_md_hellondk_MainActivity */

#ifndef _Included_com_md_hellondk_MainActivity
#define _Included_com_md_hellondk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_md_hellondk_MainActivity
 * Method:    messageFromNativeCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_md_hellondk_MainActivity_messageFromNativeCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
